name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"      # 每天 UTC 0 点自动跑一次
  workflow_dispatch:         # 允许你手动触发（测试用）

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}   # 自动读你的用户名
          outputs: |
            dist/github-snake.svg?color_snake=#ff6b6b&color_dots=#f7c948,#ff9f43,#ff6b6b,#ee5a24,#c0392b
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#ff6b6b

      - uses: peaceiris/actions-gh-pages@v4
        with:
          publish_branch: output
          publish_dir: ./dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
